services:
  claude-code-selenium-python:
    build:
      args:
        DOCKER_IMAGE_TAG_CLAUDE_CODE_PYTHON_DEVELOPMENT: ${DOCKER_IMAGE_TAG_CLAUDE_CODE_PYTHON_DEVELOPMENT:?err}
        VERSION_CHROMEDRIVER: ${VERSION_CHROMEDRIVER:?err}
      context: .
    entrypoint:
      - /bin/bash
    image: futureys/claude-code-selenium-python:development
    user: root
    volumes:
      - .:/workspace
      - /workspace/.venv
      - /workspace/.selenium-cache
      # - Using uv in Docker | uv
      #   https://docs.astral.sh/uv/guides/integration/docker/#caching
      - uv-cache:/root/.cache/uv
volumes:
  uv-cache: