on:
  push:
    tags:
      - 'v[0-9][0-9][0-9][0-9][01][0-9][0-3][0-9][0-2][0-9][0-5][0-9][0-5][0-9]'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - id: buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - id: extract-tag
        run: echo "DOCKER_TAG=$(echo ${GITHUB_REF#refs/tags/v})" >> $GITHUB_ENV
      - uses: actions/checkout@v5
      - name: Import environment variables from a file
        run: cat .env >> $GITHUB_ENV
      - uses: docker/bake-action@v6
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
